// roots02.ts is the supplementary master list of roots for 10-11 years old
// Expanded based on Science, Math, Chinese, and History textbooks
export const roots02: string[] = [
  // Science Roots/Terms
  '科学程序 (Science Process)',
  '基本需求 (Basic Needs)',
  '高度 (Height)',
  '足够 (Sufficient)',
  '骨骼 (Skeletal System)',
  '关节 (Joints)',
  '支撑 (Support)',
  '血液循环 (Circulatory System)',
  '气体交换 (Gas Exchange)',
  '生存自保 (Survival)',
  '传播方法 (Dispersal)',
  '适应环境 (Adaptation)',

  // Math Roots/Terms
  '计算指令 (Math Directives)',
  '数理概念 (Math Concepts)',
  '应用运算 (Word Problems)',

  // Chinese Lesson Roots
  '卑 (Lowly/Self)',
  '慕 (Admire)',
  '泛 (Float/General)',
  '蓬 (Overgrown)',
  '勃 (Vigorous)',
  '略 (Brief/Ignore)',
  '沮 (Depressed)',
  '丧 (Lose/Mourn)',
  '枉 (In vain)',
  '费 (Waste/Fee)',
  '漆 (Paint/Black)',
  '障 (Obstacle)',
  '碍 (Hinder)',
  '灼 (Burn/Bright)',
  '烁 (Shimmer)',
  '萤 (Firefly)',
  '囊 (Sack)',
  '翔 (Soar)',
  '恒 (Constant)',
  '毅 (Willpower)',
  '倔 (Stubborn)',
  '强 (Strong)',
  '挫 (Frustrate)',
  '馁 (Discouraged)',
  '誓 (Oath)',
  '驱 (Drive out)',
  '逐 (Chase)',
  '寇 (Bandit)',
  '碑 (Monument)',
  '崇 (Worship)',
  '敬 (Respect)',
  '扰 (Disturb)',
  '宅 (Residence)',
  '谐 (Harmonious)',
  '捷 (Convenient/Quick)',
  '敷 (Apply/Spread)',
  '衍 (Develop/Spread)',
  '恰 (Just/Proper)',
  '妥 (Appropriate)',
  '脂 (Fat/Resin)',
  '拭 (Wipe)',
  '渗 (Seep)',
  '澎 (Surge)',
  '湃 (Surge)',
  '蔼 (Friendly)',
  '揉 (Rub/Knead)',
  '膝 (Knee)',
  '愧 (Ashamed)',
  '疚 (Remorse)',
  '瞪 (Stare)',
  '恍 (Vague)',
  '惚 (Absent-minded)',

  // History/Civic Roots
  '君主制度 (Monarchy)',
  '国家主权 (Sovereignty)',
  '忠诚 (Loyalty)',
  '宗教和谐 (Religious Harmony)',
  '文化遗产 (Heritage)',
  '殖民时代 (Colonization)',
  '领袖抗争 (Local Struggle)'
];
